/*
 * com_mit_kerberos_KerberosAppActivity.h
 *
 * Copyright 1990, 2008 by the Massachusetts Institute of Technology.
 * All Rights Reserved.
 *
 * Export of this software from the United States of America may
 *   require a specific license from the United States Government.
 *   It is the responsibility of any person or organization contemplating
 *   export to obtain such a license before exporting.
 *
 * WITHIN THAT CONSTRAINT, permission to use, copy, modify, and
 * distribute this software and its documentation for any purpose and
 * without fee is hereby granted, provided that the above copyright
 * notice appear in all copies and that both that copyright notice and
 * this permission notice appear in supporting documentation, and that
 * the name of M.I.T. not be used in advertising or publicity pertaining
 * to distribution of the software without specific, written prior
 * permission.  Furthermore if you modify this software you must label
 * your software as modified software and not distribute it in such a
 * fashion that it might be confused with the original M.I.T. software.
 * M.I.T. makes no representations about the suitability of
 * this software for any purpose.  It is provided "as is" without express
 * or implied warranty.
 *
 * Original source developed by yaSSL (http://www.yassl.com)
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mit_kerberos_KerberosAppActivity */

#ifndef _Included_com_mit_kerberos_KerberosAppActivity
#define _Included_com_mit_kerberos_KerberosAppActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mit_kerberos_KerberosAppActivity
 * Method:    nativeKinit
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mit_kerberos_KerberosAppActivity_nativeKinit
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mit_kerberos_KerberosAppActivity
 * Method:    nativeKlist
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mit_kerberos_KerberosAppActivity_nativeKlist
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mit_kerberos_KerberosAppActivity
 * Method:    nativeKvno
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mit_kerberos_KerberosAppActivity_nativeKvno
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mit_kerberos_KerberosAppActivity
 * Method:    nativeKdestroy
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mit_kerberos_KerberosAppActivity_nativeKdestroy
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
