/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.jgss.swig;

public class gss_OID_desc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected gss_OID_desc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gss_OID_desc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gsswrapperJNI.delete_gss_OID_desc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

   public int hashCode() {
       return (int)swigCPtr;
   }

  public void setLength(long value) {
    gsswrapperJNI.gss_OID_desc_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return gsswrapperJNI.gss_OID_desc_length_get(swigCPtr, this);
  }

  public void setElements(String value) {
    gsswrapperJNI.gss_OID_desc_elements_set(swigCPtr, this, value);
  }

  public String getElements() {
    return gsswrapperJNI.gss_OID_desc_elements_get(swigCPtr, this);
}

  public gss_OID_desc() {
    this(gsswrapperJNI.new_gss_OID_desc__SWIG_0(), true);
  }

  public gss_OID_desc(String value) {
    this(gsswrapperJNI.new_gss_OID_desc__SWIG_1(value), true);
  }

  public gss_OID_desc(byte[] byteArray) {
    this(gsswrapperJNI.new_gss_OID_desc__SWIG_2(byteArray), true);
  }

  public int equals(String mechString_in) {
    return gsswrapperJNI.gss_OID_desc_equals(swigCPtr, this, mechString_in);
  }

  public String toString() {
    return gsswrapperJNI.gss_OID_desc_toString(swigCPtr, this);
  }

  public String toDotString() {
    return gsswrapperJNI.gss_OID_desc_toDotString(swigCPtr, this);
  }

}
