/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.jgss.swig;

public class gss_channel_bindings_struct {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected gss_channel_bindings_struct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gss_channel_bindings_struct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gsswrapperJNI.delete_gss_channel_bindings_struct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInitiator_addrtype(long value) {
    gsswrapperJNI.gss_channel_bindings_struct_initiator_addrtype_set(swigCPtr, this, value);
  }

  public long getInitiator_addrtype() {
    return gsswrapperJNI.gss_channel_bindings_struct_initiator_addrtype_get(swigCPtr, this);
  }

  public void setInitiator_address(gss_buffer_desc value) {
    gsswrapperJNI.gss_channel_bindings_struct_initiator_address_set(swigCPtr, this, gss_buffer_desc.getCPtr(value), value);
  }

  public gss_buffer_desc getInitiator_address() {
    long cPtr = gsswrapperJNI.gss_channel_bindings_struct_initiator_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_buffer_desc(cPtr, false);
  }

  public void setAcceptor_addrtype(long value) {
    gsswrapperJNI.gss_channel_bindings_struct_acceptor_addrtype_set(swigCPtr, this, value);
  }

  public long getAcceptor_addrtype() {
    return gsswrapperJNI.gss_channel_bindings_struct_acceptor_addrtype_get(swigCPtr, this);
  }

  public void setAcceptor_address(gss_buffer_desc value) {
    gsswrapperJNI.gss_channel_bindings_struct_acceptor_address_set(swigCPtr, this, gss_buffer_desc.getCPtr(value), value);
  }

  public gss_buffer_desc getAcceptor_address() {
    long cPtr = gsswrapperJNI.gss_channel_bindings_struct_acceptor_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_buffer_desc(cPtr, false);
  }

  public void setApplication_data(gss_buffer_desc value) {
    gsswrapperJNI.gss_channel_bindings_struct_application_data_set(swigCPtr, this, gss_buffer_desc.getCPtr(value), value);
  }

  public gss_buffer_desc getApplication_data() {
    long cPtr = gsswrapperJNI.gss_channel_bindings_struct_application_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_buffer_desc(cPtr, false);
  }

  public gss_channel_bindings_struct() {
    this(gsswrapperJNI.new_gss_channel_bindings_struct(), true);
  }

}
