/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.jgss.swig;

public class gss_OID_set_desc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected gss_OID_set_desc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gss_OID_set_desc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gsswrapperJNI.delete_gss_OID_set_desc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(long value) {
    gsswrapperJNI.gss_OID_set_desc_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return gsswrapperJNI.gss_OID_set_desc_count_get(swigCPtr, this);
  }

  public void setElements(gss_OID_desc value) {
    gsswrapperJNI.gss_OID_set_desc_elements_set(swigCPtr, this, gss_OID_desc.getCPtr(value), value);
  }

  public gss_OID_desc getElements() {
    long cPtr = gsswrapperJNI.gss_OID_set_desc_elements_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_OID_desc(cPtr, false);
  }

  public gss_OID_set_desc() {
    this(gsswrapperJNI.new_gss_OID_set_desc(), true);
  }

  public gss_OID_desc getElement(int offset) {
    long cPtr = gsswrapperJNI.gss_OID_set_desc_getElement(swigCPtr, this, offset);
    return (cPtr == 0) ? null : new gss_OID_desc(cPtr, false);
  }

}
