/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.jgss.swig;

public class gss_buffer_desc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected gss_buffer_desc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gss_buffer_desc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gsswrapperJNI.delete_gss_buffer_desc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLength(long value) {
    gsswrapperJNI.gss_buffer_desc_length_set(swigCPtr, this, value);
  }

  public long getLength() {
    return gsswrapperJNI.gss_buffer_desc_length_get(swigCPtr, this);
  }

  public void setValue(String value) {
    gsswrapperJNI.gss_buffer_desc_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return gsswrapperJNI.gss_buffer_desc_value_get(swigCPtr, this);
}

  public gss_buffer_desc() {
    this(gsswrapperJNI.new_gss_buffer_desc__SWIG_0(), true);
  }

  public gss_buffer_desc(String value) {
    this(gsswrapperJNI.new_gss_buffer_desc__SWIG_1(value), true);
  }

  public String toString() {
    return gsswrapperJNI.gss_buffer_desc_toString(swigCPtr, this);
  }

}
