/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.jgss.swig;

public class gss_name_t_desc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected gss_name_t_desc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gss_name_t_desc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gsswrapperJNI.delete_gss_name_t_desc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLoopback(gss_name_t_desc value) {
    gsswrapperJNI.gss_name_t_desc_loopback_set(swigCPtr, this, gss_name_t_desc.getCPtr(value), value);
  }

  public gss_name_t_desc getLoopback() {
    long cPtr = gsswrapperJNI.gss_name_t_desc_loopback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_name_t_desc(cPtr, false);
  }

  public void setName_type(gss_OID_desc value) {
    gsswrapperJNI.gss_name_t_desc_name_type_set(swigCPtr, this, gss_OID_desc.getCPtr(value), value);
  }

  public gss_OID_desc getName_type() {
    long cPtr = gsswrapperJNI.gss_name_t_desc_name_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_OID_desc(cPtr, false);
  }

  public void setExternal_name(gss_buffer_desc value) {
    gsswrapperJNI.gss_name_t_desc_external_name_set(swigCPtr, this, gss_buffer_desc.getCPtr(value), value);
  }

  public gss_buffer_desc getExternal_name() {
    long cPtr = gsswrapperJNI.gss_name_t_desc_external_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_buffer_desc(cPtr, false);
  }

  public void setMech_type(gss_OID_desc value) {
    gsswrapperJNI.gss_name_t_desc_mech_type_set(swigCPtr, this, gss_OID_desc.getCPtr(value), value);
  }

  public gss_OID_desc getMech_type() {
    long cPtr = gsswrapperJNI.gss_name_t_desc_mech_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_OID_desc(cPtr, false);
  }

  public void setMech_name(gss_name_t_desc value) {
    gsswrapperJNI.gss_name_t_desc_mech_name_set(swigCPtr, this, gss_name_t_desc.getCPtr(value), value);
  }

  public gss_name_t_desc getMech_name() {
    long cPtr = gsswrapperJNI.gss_name_t_desc_mech_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gss_name_t_desc(cPtr, false);
  }

  public gss_name_t_desc() {
    this(gsswrapperJNI.new_gss_name_t_desc(), true);
  }

}
