/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.mit.jgss.swig;

public interface gsswrapperConstants {
  public final static int GSS_C_DELEG_FLAG = gsswrapperJNI.GSS_C_DELEG_FLAG_get();
  public final static int GSS_C_MUTUAL_FLAG = gsswrapperJNI.GSS_C_MUTUAL_FLAG_get();
  public final static int GSS_C_REPLAY_FLAG = gsswrapperJNI.GSS_C_REPLAY_FLAG_get();
  public final static int GSS_C_SEQUENCE_FLAG = gsswrapperJNI.GSS_C_SEQUENCE_FLAG_get();
  public final static int GSS_C_CONF_FLAG = gsswrapperJNI.GSS_C_CONF_FLAG_get();
  public final static int GSS_C_INTEG_FLAG = gsswrapperJNI.GSS_C_INTEG_FLAG_get();
  public final static int GSS_C_ANON_FLAG = gsswrapperJNI.GSS_C_ANON_FLAG_get();
  public final static int GSS_C_PROT_READY_FLAG = gsswrapperJNI.GSS_C_PROT_READY_FLAG_get();
  public final static int GSS_C_TRANS_FLAG = gsswrapperJNI.GSS_C_TRANS_FLAG_get();
  public final static int GSS_C_DELEG_POLICY_FLAG = gsswrapperJNI.GSS_C_DELEG_POLICY_FLAG_get();
  public final static int GSS_C_BOTH = gsswrapperJNI.GSS_C_BOTH_get();
  public final static int GSS_C_INITIATE = gsswrapperJNI.GSS_C_INITIATE_get();
  public final static int GSS_C_ACCEPT = gsswrapperJNI.GSS_C_ACCEPT_get();
  public final static int GSS_C_GSS_CODE = gsswrapperJNI.GSS_C_GSS_CODE_get();
  public final static int GSS_C_MECH_CODE = gsswrapperJNI.GSS_C_MECH_CODE_get();
  public final static int GSS_C_AF_UNSPEC = gsswrapperJNI.GSS_C_AF_UNSPEC_get();
  public final static int GSS_C_AF_LOCAL = gsswrapperJNI.GSS_C_AF_LOCAL_get();
  public final static int GSS_C_AF_INET = gsswrapperJNI.GSS_C_AF_INET_get();
  public final static int GSS_C_AF_IMPLINK = gsswrapperJNI.GSS_C_AF_IMPLINK_get();
  public final static int GSS_C_AF_PUP = gsswrapperJNI.GSS_C_AF_PUP_get();
  public final static int GSS_C_AF_CHAOS = gsswrapperJNI.GSS_C_AF_CHAOS_get();
  public final static int GSS_C_AF_NS = gsswrapperJNI.GSS_C_AF_NS_get();
  public final static int GSS_C_AF_NBS = gsswrapperJNI.GSS_C_AF_NBS_get();
  public final static int GSS_C_AF_ECMA = gsswrapperJNI.GSS_C_AF_ECMA_get();
  public final static int GSS_C_AF_DATAKIT = gsswrapperJNI.GSS_C_AF_DATAKIT_get();
  public final static int GSS_C_AF_CCITT = gsswrapperJNI.GSS_C_AF_CCITT_get();
  public final static int GSS_C_AF_SNA = gsswrapperJNI.GSS_C_AF_SNA_get();
  public final static int GSS_C_AF_DECnet = gsswrapperJNI.GSS_C_AF_DECnet_get();
  public final static int GSS_C_AF_DLI = gsswrapperJNI.GSS_C_AF_DLI_get();
  public final static int GSS_C_AF_LAT = gsswrapperJNI.GSS_C_AF_LAT_get();
  public final static int GSS_C_AF_HYLINK = gsswrapperJNI.GSS_C_AF_HYLINK_get();
  public final static int GSS_C_AF_APPLETALK = gsswrapperJNI.GSS_C_AF_APPLETALK_get();
  public final static int GSS_C_AF_BSC = gsswrapperJNI.GSS_C_AF_BSC_get();
  public final static int GSS_C_AF_DSS = gsswrapperJNI.GSS_C_AF_DSS_get();
  public final static int GSS_C_AF_OSI = gsswrapperJNI.GSS_C_AF_OSI_get();
  public final static int GSS_C_AF_NETBIOS = gsswrapperJNI.GSS_C_AF_NETBIOS_get();
  public final static int GSS_C_AF_X25 = gsswrapperJNI.GSS_C_AF_X25_get();
  public final static int GSS_C_AF_NULLADDR = gsswrapperJNI.GSS_C_AF_NULLADDR_get();
  public final static gss_name_t_desc GSS_C_NO_NAME = new gss_name_t_desc(gsswrapperJNI.GSS_C_NO_NAME_get(), false);
  public final static gss_buffer_desc GSS_C_NO_BUFFER = new gss_buffer_desc(gsswrapperJNI.GSS_C_NO_BUFFER_get(), false);
  public final static gss_OID_desc GSS_C_NO_OID = new gss_OID_desc(gsswrapperJNI.GSS_C_NO_OID_get(), false);
  public final static gss_OID_set_desc GSS_C_NO_OID_SET = new gss_OID_set_desc(gsswrapperJNI.GSS_C_NO_OID_SET_get(), false);
  public final static gss_ctx_id_t_desc GSS_C_NO_CONTEXT = new gss_ctx_id_t_desc(gsswrapperJNI.GSS_C_NO_CONTEXT_get(), false);
  public final static gss_cred_id_t_desc GSS_C_NO_CREDENTIAL = new gss_cred_id_t_desc(gsswrapperJNI.GSS_C_NO_CREDENTIAL_get(), false);
  public final static gss_channel_bindings_struct GSS_C_NO_CHANNEL_BINDINGS = new gss_channel_bindings_struct(gsswrapperJNI.GSS_C_NO_CHANNEL_BINDINGS_get(), false);
  public final static gss_buffer_desc GSS_C_EMPTY_BUFFER = new gss_buffer_desc(gsswrapperJNI.GSS_C_EMPTY_BUFFER_get(), false);
  public final static int GSS_C_QOP_DEFAULT = gsswrapperJNI.GSS_C_QOP_DEFAULT_get();
  public final static int GSS_C_INDEFINITE = gsswrapperJNI.GSS_C_INDEFINITE_get();
  public final static int GSS_S_COMPLETE = gsswrapperJNI.GSS_S_COMPLETE_get();
  public final static int GSS_C_CALLING_ERROR_OFFSET = gsswrapperJNI.GSS_C_CALLING_ERROR_OFFSET_get();
  public final static int GSS_C_ROUTINE_ERROR_OFFSET = gsswrapperJNI.GSS_C_ROUTINE_ERROR_OFFSET_get();
  public final static int GSS_C_SUPPLEMENTARY_OFFSET = gsswrapperJNI.GSS_C_SUPPLEMENTARY_OFFSET_get();
  public final static long GSS_C_CALLING_ERROR_MASK = gsswrapperJNI.GSS_C_CALLING_ERROR_MASK_get();
  public final static long GSS_C_ROUTINE_ERROR_MASK = gsswrapperJNI.GSS_C_ROUTINE_ERROR_MASK_get();
  public final static long GSS_C_SUPPLEMENTARY_MASK = gsswrapperJNI.GSS_C_SUPPLEMENTARY_MASK_get();
  public final static int GSS_S_CALL_INACCESSIBLE_READ = gsswrapperJNI.GSS_S_CALL_INACCESSIBLE_READ_get();
  public final static int GSS_S_CALL_INACCESSIBLE_WRITE = gsswrapperJNI.GSS_S_CALL_INACCESSIBLE_WRITE_get();
  public final static int GSS_S_CALL_BAD_STRUCTURE = gsswrapperJNI.GSS_S_CALL_BAD_STRUCTURE_get();
  public final static int GSS_S_BAD_MECH = gsswrapperJNI.GSS_S_BAD_MECH_get();
  public final static int GSS_S_BAD_NAME = gsswrapperJNI.GSS_S_BAD_NAME_get();
  public final static int GSS_S_BAD_NAMETYPE = gsswrapperJNI.GSS_S_BAD_NAMETYPE_get();
  public final static int GSS_S_BAD_BINDINGS = gsswrapperJNI.GSS_S_BAD_BINDINGS_get();
  public final static int GSS_S_BAD_STATUS = gsswrapperJNI.GSS_S_BAD_STATUS_get();
  public final static int GSS_S_BAD_SIG = gsswrapperJNI.GSS_S_BAD_SIG_get();
  public final static int GSS_S_NO_CRED = gsswrapperJNI.GSS_S_NO_CRED_get();
  public final static int GSS_S_NO_CONTEXT = gsswrapperJNI.GSS_S_NO_CONTEXT_get();
  public final static int GSS_S_DEFECTIVE_TOKEN = gsswrapperJNI.GSS_S_DEFECTIVE_TOKEN_get();
  public final static int GSS_S_DEFECTIVE_CREDENTIAL = gsswrapperJNI.GSS_S_DEFECTIVE_CREDENTIAL_get();
  public final static int GSS_S_CREDENTIALS_EXPIRED = gsswrapperJNI.GSS_S_CREDENTIALS_EXPIRED_get();
  public final static int GSS_S_CONTEXT_EXPIRED = gsswrapperJNI.GSS_S_CONTEXT_EXPIRED_get();
  public final static int GSS_S_FAILURE = gsswrapperJNI.GSS_S_FAILURE_get();
  public final static int GSS_S_BAD_QOP = gsswrapperJNI.GSS_S_BAD_QOP_get();
  public final static int GSS_S_UNAUTHORIZED = gsswrapperJNI.GSS_S_UNAUTHORIZED_get();
  public final static int GSS_S_UNAVAILABLE = gsswrapperJNI.GSS_S_UNAVAILABLE_get();
  public final static int GSS_S_DUPLICATE_ELEMENT = gsswrapperJNI.GSS_S_DUPLICATE_ELEMENT_get();
  public final static int GSS_S_NAME_NOT_MN = gsswrapperJNI.GSS_S_NAME_NOT_MN_get();
  public final static int GSS_S_BAD_MECH_ATTR = gsswrapperJNI.GSS_S_BAD_MECH_ATTR_get();
  public final static int GSS_S_CONTINUE_NEEDED = gsswrapperJNI.GSS_S_CONTINUE_NEEDED_get();
  public final static int GSS_S_DUPLICATE_TOKEN = gsswrapperJNI.GSS_S_DUPLICATE_TOKEN_get();
  public final static int GSS_S_OLD_TOKEN = gsswrapperJNI.GSS_S_OLD_TOKEN_get();
  public final static int GSS_S_UNSEQ_TOKEN = gsswrapperJNI.GSS_S_UNSEQ_TOKEN_get();
  public final static int GSS_S_GAP_TOKEN = gsswrapperJNI.GSS_S_GAP_TOKEN_get();
  public final static int GSS_C_PRF_KEY_FULL = gsswrapperJNI.GSS_C_PRF_KEY_FULL_get();
  public final static int GSS_C_PRF_KEY_PARTIAL = gsswrapperJNI.GSS_C_PRF_KEY_PARTIAL_get();
  public final static int GSS_S_CRED_UNAVAIL = gsswrapperJNI.GSS_S_CRED_UNAVAIL_get();
}
